package com.zxsd.common;

public class Constants {
	public static final String HTML_INDEX_TYPE="1" ;//频道首页
	public static final String HTML_TOPS_TYPE="2" ;//顶部
	public static final String HTML_FOOTS_TYPE="3" ;//底部
	public static final String HTML_WORD_TYPE="4" ;//词条
	public static final String HTML_WORDATTR_TYPE="5" ;//词条维度
	public static final String HTML_ARTICLE_TYPE="6" ;//文章
	public static final String HTML_CONTENTMAP_TYPE="7" ;//词条文章地图
	public static final String HTML_HUATI_TYPE="10" ;//话题
	public static final String HTML_THEME_TYPE="9" ;//专题
	public static final String HTML_SURVEY_TYPE="8" ;//调查问卷
	public static final String HTML_WAPINDEX_TYPE="10" ;//wap首页
	public static final String HTML_WAPCHANNEL_TYPE="11" ;//wap频道页
	public static final String INDEX_JRJD = "127";//今日焦点
	public static final String INDEX_JTBL = "128";//惊天曝料
	public static final String INDEX_SYZY = "151";//首页摘要
	public static final String BGT_MEMXS = "104";//曝光线索
	public static final String BGT_XWZX = "107";//新闻资讯
	public static final String BGT_QWFB = "108";//权威发布
	public static final String BGT_ZCJD = "109";//政策解读
	public static final String BGT_HABL = "110";//黑暗爆料
	public static final String BGT_BGPP = "105";//曝光品牌
	public static final String BGT_BGQY = "106";//曝光企业
	public static final String YZPP_PPXW = "111";//品牌新闻
	public static final String YZPP_PPGS = "112";//品牌故事
	public static final String YZPP_PPRW = "113";//品牌人物
	public static final String SH_GZSC = "116";//故障手册
	public static final String SH_WXTS = "117";//温馨提示
	public static final String SH_FWLC = "118";//服务流程
	public static final String SH_FWBZ = "119";//服务标准
	public static final String SH_DZZL = "136";//说明书/电子资料下载
	public static final String SH_YJYF = "137";//药剂用法及服用禁忌
	public static final String SH_YLQQ = "138";//医疗器械使用方法
	public static final String SH_JJWH = "139";//家装/家具/家居维护说明
	public static final String SH_FZXM = "140";//服装鞋包饰品搭配指南
	public static final String SH_YHSC = "141";//用户手册/尺码对照表
	public static final String SH_YHHD = "120";//优惠活动
	public static final String BZ_ZCFG = "103";//政策法规
	public static final String BZ_ALJX = "148";//案例解析
	public static final String ZXSD_HTML = "zxsd_html";//静态页面项目名称
	public static final String LOG_ERROR = "ERROR";//日志级别
	public static final String LOG_INFO = "INFO";//日志级别
	public static final String LOG_WARN = "WARN";//日志级别
	public static final String LOG_OPERA_SYS = "SYS";//日志操作类型
	public static final String LOG_OPERA_UYS = "UYS";//日志操作类型
	public static final String LOG_OPERA_QUERY = "QUERY";//查询行为
	public static final String LOG_OPERA_UPDATE = "UPDATE";//更新行为
	public static final String LOG_OPERA_DELETE = "DELETE";//删除行为
	public static final String LOG_OPERA_ADD = "SAVE";//增加行为
	public static final String LOG_OPERA_SUCCESS = "SUCCESS";//操作成功
	public static final String LOG_OPERA_FAIL = "FAIL";//操作失败
	
	public static final String ZXSD_YJINDEX_ID = "103";//购买依据
	public static final String ZXSD_JQINDEX_ID = "104";//购买技巧
	public static final String ZXSD_TSINDEX_ID = "105";//购买提示
	public static final String ZXSD_WQINDEX_ID = "106";//购买误区
	public static final String ZXSD_XJINDEX_ID = "107";//购买陷阱
	public static final String ZXSD_LCINDEX_ID = "108";//购买流程
	public static final String ZXSD_BZINDEX_ID = "109";//国家标准
	public static final String ZXSD_BGTINDEX_ID = "101";//曝光台
	public static final String ZXSD_PPINDEX_ID = "110";//优质品牌
	public static final String ZXSD_HLINDEX_ID = "111";//保养护理
	public static final String ZXSD_SHINDEX_ID = "112";//售后服务
	public static final String ZXSD_FXINDEX_ID = "102";//经验分享
	public static final String ZXSD_TJINDEX_ID = "114";//图集
	public static final String INDEX_JD_NAME = "今日焦点";
	public static final String INDEX_BL_NAME = "惊天曝料";
	public static final String INDEX_ZY_NAME = "首页摘要";
	public static final String INDEX_JQ_NAME= "购买技巧";
	public static final String INDEX_YJ_NAME = "购买依据";
	public static final String INDEX_TS_NAME = "购买提示";
	public static final String INDEX_WQ_NAME = "购买误区";
	public static final String INDEX_XJ_NAME = "购买陷阱";
	public static final String INDEX_LC_NAME = "购买流程";
	public static final String INDEX_BG_NAME = "曝光台";
	public static final String INDEX_BZ_NAME= "国家标准";
	public static final String INDEX_YP_NAME = "优质品牌";
	public static final String INDEX_HL_NAME = "保养护理";
	public static final String INDEX_FW_NAME = "售后服务";
	public static final String INDEX_FX_NAME = "经验分享";
	public static final String INDEX_ZK_NAME = "优惠折扣";

	public static final String INDEX_YPFW_GOODS_LIST = "101,105,106,104,107,109,102,113,115,108,112";//优质品牌、售后服务分类

	public static final String ZXSD_IP_ADDRESS = "222.128.44.204";//
}
